### ISSUE TITLE
The readme claims that the old API (< v10) is still supported, but it does not appear to be the case

### ISSUE THREAD

**Issue by sjrd** [tmpvar/jsdom#1820]
### Basic info:

- **Node.js version:** v6.3.1
- **jsdom version:** v10.0.0
- **OS:** Windows (I haven't tested on another OS yet)

### Minimal reproduction case

Trivial usage of the old API:

```js
const jsdom = require("jsdom");
jsdom.createVirtualConsole();
// or
jsdom.env({
  html: ""
});
```
causes:
```
jsdom.createVirtualConsole();
      ^

TypeError: jsdom.createVirtualConsole is not a function
    at Object.<anonymous> (C:\Users\Sepi\Documents\Projets\jsdom-old-api-bug\jsdom-old-api-bug.js:2:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```
or
```
jsdom.env({
      ^

TypeError: jsdom.env is not a function
    at Object.<anonymous> (C:\Users\Sepi\Documents\Projets\jsdom-old-api-bug\jsdom-old-api-bug.js:4:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```
The above snippet works with jsdom 9.12.0.

I'm pretty sure I missed something and that it's actually my own fault, but since I didn't find an existing bug report on the topic, I figured I'd file it anyway.

**Comment by sjrd** [comment]
OK sorry, I was being dumb. After re-reading [the documentation of the old API](https://github.com/tmpvar/jsdom/blob/master/lib/old-api.md), I noticed that the `require` statement needs to be adapted. Perhaps this deserves to be highlighted somewhere? Or perhaps it was already highlighted and I missed it anyway.

To support both jsdom v9 and v10, I end up using:
```js
var jsdom;
try {
  jsdom = require("jsdom/lib/old-api.js"); // jsdom >= 10.x
} catch (e) {
  jsdom = require("jsdom"); // jsdom <= 9.x
}
```
Sorry again for the noise. I'm a big fan of jsdom; it replaced PhantomJS as the default DOM-enabled environment for Scala.js users.
