### ISSUE TITLE
Browser tests are now failing with "fs.createReadStream is not a function"

### ISSUE THREAD

**Issue by domenic** [tmpvar/jsdom#1428]
Even seemingly innocuous tests, like the level1 and level2 tests, are now triggering this. Not sure if this was one of the recent commits, or some dependency update (browserify?), or what... Help appreciated.

**Comment by domenic** [comment]
Caused by https://github.com/tmpvar/jsdom/commit/1773d704b819f76b609a447345dfc01e96a5d474, hmm. @nicolashenry any ideas? Once you get the environment set up, you do `npm run test-browser` to reproduce. You didn't change a lot of things in resource-loader.js, so I am not sure why this would start breaking...

**Comment by nicolashenry** [comment]
Oh sorry, I forgot those tests, I will take a look as soon as possible.

**Comment by domenic** [comment]
I think I found part of it. Some of our test fixtures were referencing non-existant script files. Somehow your work (maybe the changes to HTMLScriptElement?) un-hid that bug.

I think I have a fix; will push it soon.

**Comment by domenic** [comment]
This should be all taken care of now :)

**Comment by nicolashenry** [comment]
Oh ok, nice :)
