### ISSUE TITLE
TypeError: tree.$TreeIterator_node is not a function when trying to build DOM

### ISSUE THREAD

**Issue by swanson** [tmpvar/jsdom#1282]
jsdom@7.0.2 (Windows, Node v4.2.1)

I'm trying to setup a fake DOM for testing React (with Mocha), using a snippet that is found in several blog examples:

```js
module.exports = function() {
    if (typeof document !== 'undefined') return;
    var jsdom = require('jsdom');
    global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
    global.window = document.defaultView;
    global.navigator = {
        userAgent: 'node.js'
    };
}
```

I'm getting this exception:
```shell
this[NEXT] = tree.$TreeIterator_node(value).parent;
                                          ^

TypeError: tree.$TreeIterator_node is not a function
    at TreeIterator.Object.defineProperty.value (C:\dev\foobar\node_modules\jsdom\node_modules\symbol-tree\lib\TreeIterator.js:37:43)
    at HTMLDocument.core.Node.insertBefore (C:\dev\foobar\node_modules\jsdom\lib\jsdom\level1\core.js:292:42)
    at HTMLDocument.core.Node.insertBefore (C:\dev\foobar\node_modules\jsdom\lib\jsdom\level2\events.js:207:32)
    at HTMLDocument.core.Node.appendChild (C:\dev\foobar\node_modules\jsdom\lib\jsdom\level1\core.js:535:17)
    at HTMLDocument.inheritFrom.appendChild (C:\dev\foobar\node_modules\jsdom\lib\jsdom\level1\core.js:877:44)
    at setChild (C:\dev\foobar\node_modules\jsdom\lib\jsdom\browser\htmltodom.js:191:17)
    at HtmlToDom.appendHtmlToElement [as appendHtmlToDocument] (C:\dev\foobar\node_modules\jsdom\lib\jsdom\browser\htmltodom.js:58:9)
    at setInnerHTML (C:\dev\foobar\node_modules\jsdom\lib\jsdom\level1\core.js:64:27)
    at HTMLDocument.inheritFrom.write (C:\dev\foobar\node_modules\jsdom\lib\jsdom\level1\core.js:953:7)
    at Object.exports.jsdom (C:\dev\foobar\node_modules\jsdom\lib\jsdom.js:115:21)
``` 

on the line `global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');`

Any ideas? Is this a Windows issue? Something with my Mocha setup? Am I using jsdom incorrectly?

**Comment by swanson** [comment]
The above code appears to work with jsdom@5.1.0 -- not sure if that helps :)

**Comment by domenic** [comment]
(Gah, why do people keep attaching jsdom variables to the global... so bad... probably not the cause of this though.)

The script you gave of course does nothing by itself, so this isn't exactly testable with what you showed. What about this script? Does it cause the error, when you save it as `test.js` and do `node test.js`?

```js
    var jsdom = require('jsdom');
    global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
    global.window = document.defaultView;
    global.navigator = {
        userAgent: 'node.js'
    };
```

**Comment by swanson** [comment]
@domenic apologies for not providing something you could run.

Running the code you posted does not cause an error, so that leads me to believe the issue might not be within jsdom, but rather the test setup with mocha/react.
